### ISSUE TITLE
these cases should throw exception

### ISSUE THREAD

**Issue by fishbar** [sindresorhus/multiline#27]
this case should throw exception:
```
multiline(function () {
// test invalid content
/*
valid content
*/
});
```

this case should throw too:
```
multiline(function () {
/*
valid content
*/
/*
valid content 2
*/
});
```

**Comment by sindresorhus** [comment]
Why? Have you encountered this? There are a multitude of ways to do it wrong. Not sure it's worth adding lots of complications for checking for that.

**Comment by fishbar** [comment]
because strict always good for code

**Comment by sindresorhus** [comment]
PR welcome, but going to close this as I don't have any interest in doing this myself.
