### ISSUE TITLE
UglifyJS2 comments are not preserved

### ISSUE THREAD

**Issue by gaborbernat** [sindresorhus/multiline#28]
:) Any ideas?

**Comment by sindresorhus** [comment]
Did you read the readme?

**Comment by gaborbernat** [comment]
Sure, but adding either @preserve or /!* is stripped, I found multiple uglifyjs2 tickets related to this: https://github.com/mishoo/UglifyJS2/issues/88

**Comment by sindresorhus** [comment]
Tests are passing with latest UglifyJS2, so you're doing something wrong: https://github.com/sindresorhus/multiline/blob/15fb0961727e9bbad2ecc1ad54508cf01678e6d5/test.js#L72-L84

Make sure you've read everything here: https://github.com/sindresorhus/multiline#minification

**Comment by kevva** [comment]
@gaborbernat, could you share your code?

**Comment by gaborbernat** [comment]
I'll try to make a demo of this next week as the actual source code is
trade mark :)

**Comment by sindresorhus** [comment]
@gaborbernat Even better, submit a failing test if possible ;)

**Comment by gaborbernat** [comment]
Oh, you're right, I'll try it :)
