### ISSUE TITLE
How do I build with the experiement.js

### ISSUE THREAD

**Issue by RYJASM** [sindresorhus/multiline#33]
Not super familiar with npm. How do I build the library using the exeriment.js file?

**Comment by SamVerschueren** [comment]
What do you mean with `experiment.js`? Also this seems more like a question for that project. It should support npm packages.

**Comment by RYJASM** [comment]
Basically I want a library file for multiline.js that I can include in an html file and then call the multiline function and use it. How do I get that?

**Comment by RYJASM** [comment]
See here about the "exeriment.js" file: https://github.com/sindresorhus/multiline#experiment

**Comment by SamVerschueren** [comment]
The experiment has nothing to do with embedding the module on a website. If you want node modules in your web app you will have to use a module bundler like Webpack, SystemJS, browserify, etc.

Another alternative for this is to use `unpkg.com` and embed that in your webapp. But I would suggest not doing that and look at module bundlers as they are way more powerfull.

https://unpkg.com/multiline.js@1.0.2/multiline.js

**Comment by RYJASM** [comment]
Thanks for the info. But wouldn't the default build not be using the experiement.js method? How would I build the library so that it will use that method?

**Comment by SamVerschueren** [comment]
Don't use it, as per the docs

> It's too fragile and slow to be practical though.

**Comment by RYJASM** [comment]
That doesn't really answer the question though haha. I want to try it.

**Comment by SamVerschueren** [comment]
There also seem to be a browser version: https://github.com/sindresorhus/multiline/blob/master/browser.js

No I don't see any easy way of doing that because (a) that file is not shipped to `npm` and (b) it is using [callsites](https://github.com/sindresorhus/callsites) which is another dependency so you would have to use a module bundler or hack everything together yourself.
